default: &default
  adapter: postgresql
  pool: 5
  encoding: SQL_ASCII
  username: postgres
  password: 6312139
  
development:
  <<: *default
  database: developmentpg

test:
  <<: *default
  database: testpg
