default: &default
  adapter: postgresql
  pool: 5
  encoding: UTF8
  username: yunnan
  password: 6312139
  
development:
  <<: *default
  database: developmentpg

test:
  <<: *default
  database: testpg
production:
  adapter: postgresql
  encoding: unicode
  database: productionpg